use std::env;

use cbindgen::Language;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(Language::C)
        .with_autogen_warning("/* This file was automatically generated by cbindgen */")
        .with_item_prefix("cao_")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("cao-lang.h");
}
