use std::env;

use cbindgen::Language;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let builder = cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(Language::C)
        .with_autogen_warning("/* This file was automatically generated by cbindgen */")
        .with_item_prefix("cao_")
        .with_include_guard("CAO_LANG_H");

    #[cfg(target_os = "windows")]
    let builder = {
        const WINDOWS_LIBS: &str = r#"
#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "userenv.lib")
#pragma comment(lib, "advapi32.lib")"#;
        builder.with_after_include(WINDOWS_LIBS)
    };
    builder
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("include/cao-lang.h");
}
