[package]
name = "cao-lang-wasm"
version = "0.1.34"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]
edition = "2018"
description = "Wrapper of [CaoLang](https://github.com/caolo-game/cao-lang.git)"
license = "MIT"
repository = "https://github.com/caolo-game/cao-lang"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
cao-lang = { path = "../cao-lang", features = ["serde"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
serde = "1"
serde_derive = "1"
js-sys = "0.3"
wasm-logger = "0.2"
console_error_panic_hook = { version = "0.1.1", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"
serde_json = "1"

# wasm panics without this so there we go
# see: https://ritik-mishra.medium.com/resolving-the-wasm-pack-error-locals-exceed-maximum-ec3a9d96685b
[profile.dev]
opt-level = 1
incremental = true

[profile.release]
opt-lezel = "z"
