build:
	wasm-pack build --target web --scope caolo-game --dev -d out/pkg

release:
	wasm-pack build --target web --scope caolo-game --release -d out/pkg -- --no-default-features

test:
	cargo check
	wasm-pack test --node
	wasm-pack test --firefox --headless

pack: release
	wasm-pack pack out/pkg

publish: release
	cd out/pkg && npm publish --access=public

link: pack
    cd out/pkg && npm link
