name: C bindings tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash
    working-directory: c

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Test C binding builds
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.18.x'

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DCAOLO_ENABLE_TESTING=ON
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
