name: Run Cao-Lang C binding tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash
    working-directory: c

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Test C binding builds
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.3
        with:
          config: Debug
          submodule_update: OFF
          run_tests: OFF
          unit_test_build:
          cmake_args: -DCAOLO_ENABLE_TESTING=ON
          create_package: OFF

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
