name: Cao-Lang core publish

on:
  push:
    branches: [master, main]
    tags: "*"
  pull_request:
    branches: [master, main]


defaults:
  run:
    shell: bash
    working-directory: cao-lang

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Publish
        if: ${{ github.event.ref_type == 'tag' }}
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          path: "./cao-lang"
