name: CLI Release

on:
  push:
    tags: 
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: caoc
          - os: macos-latest
            binary: caoc
          - os: windows-latest
            binary: caoc.exe

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd cli
        cargo build --release
    - name: Upload asset to release
      # You may pin to the exact commit or the version.
      # uses: gacts/upload-to-release@1145ecc7e15a442c563ae3050991b7c211030377
      uses: gacts/upload-to-release@v1.0.1
      with:
        # Input file
        file: cli/target/release/${{matrix.binary}}
        # File type
        type: application/binary
        # Dry run (true|false)
        dry: true      
