name: CLI Release

on:
  push:
    tags: 
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: caoc
          - os: macos-latest
            binary: caoc
          - os: windows-latest
            binary: caoc.exe

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd cli
        cargo build --release
    - name: Upload asset to release
      uses: gacts/upload-to-release@v1.0.1
      with:
        file: ./cli/target/release/${{matrix.binary}}
        type: application/binary
        dry: false
