name: Python tests

on:
  push:
    branches: [master, main]
    tags: [v*]
  pull_request:
    branches: [master, main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: "Setup Python"
        uses: actions/setup-python@v2.2.1
        with:
          python-versions: ["3.9", "3.8", "3.7", "3.6"]

      - run: pip install tox
      - run: tox -q -p auto
