name: Python tests

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: "Setup Python 39"
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: "Setup Python 38"
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: "Setup Python 36"
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.6

      - run: pip install tox
      - run: tox -q -p auto
  distribute:
    strategy:
      matrix:
        python: ["3.9", "3.8", "3.6"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Python ${{matrix.python}}"
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{matrix.python}}
      - name: "Install build dependencies"
        run: pip install build twine
      - name: "Build distributions"
        run: python -m build --sdist --wheel
      - name: "Upload"
        run: twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: 1
