name: "Run tests"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
