on: [push, pull_request]

name: Run WASM tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Chrome
        run: |
          cd cao-lang-wasm
          wasm-pack test --headless --chrome

      - name: FireFox
        run: |
          cd cao-lang-wasm
          wasm-pack test --headless --firefox
